### ISSUE TITLE
[Need Help] DeviceNotFound

### ISSUE THREAD

**Issue by isatria** [lepiaf/serialport#2]
The error exception says that the device is not found

>  (device path does not exist)
SerialPort.php line `63`

![1](https://user-images.githubusercontent.com/9941418/41820902-3cb3ceea-7803-11e8-8d98-3e1ffde5a8f3.JPG)

Though I should have all the correct configuration because I only have one serial port connected
![3](https://user-images.githubusercontent.com/9941418/41820996-6f848610-7804-11e8-93e1-6a1fbc04f6b8.JPG)

**NB:
Serial works well when testing through powershell**
![2](https://user-images.githubusercontent.com/9941418/41820977-47336b5e-7804-11e8-88f7-01a8c4af7325.JPG)

**Comment by lepiaf** [comment]
Hi,

I don't have any hint for you. Basically, it use fopen to read serial port.

Maybe php does not have right to list all COM* port.

**Comment by MrFiregore** [comment]
I think that you had this error because the path that the library uses was made for linux. 
You need modify the path to the tty file
