### ISSUE TITLE
Provide documentation

### ISSUE THREAD

**Issue by DRSDavidSoft** [lepiaf/serialport#3]
Can you provide some documentation for the Class apis and about all the options in `TTYConfigure`?

I'm especially interested in [disabling `dtr`](https://stackoverflow.com/questions/36100516/linux-serial-disable-dtr-php) (causes Arduino to reset on port open when enabled), and using multiple characters for the seperators.

I think the flag is `hupcl`.

**Comment by lepiaf** [comment]
Hi,

I don't know exactly what does each option. I've grab it from forums I've found while I did my research. Basically, each option come from `stty` command. Do a `man stty` for more information.

If you want to add flag, you can do 
```
$ttyConfigure = new TTYConfigure();
$ttyConfigure->setOption('hupcl', true);

$serialPort = new SerialPort(new SeparatorParser(), $ttyConfigure);
```

For separator, you can implement your own separator. You can find how it is use here https://github.com/lepiaf/serialport/blob/master/src/lepiaf/SerialPort/SerialPort.php#L113

For exemple, serial port will output `hello world\n` and you will get string `hello world`. If you configure `new SeparatorParser('hello')`, you will only get ` world\n`.

I hope I've answered your question.

Regards,

**Comment by lepiaf** [comment]
As workaround for Arduino reboot, I've put a string ("ready") in setup bloc and wait it in my php program. Then I know that arduino is ready.

**Comment by DRSDavidSoft** [comment]
@lepiaf Thanks for the reply!

As for the workaround, I already use something like this:

```
void setup()
{
	Serial.println (F("Arduino: Device Ready."));
}
```

However, the problem with this approach is that the microcontroller loses context (memory variables and current running function) when it is reset, and the [Optiboot bootloader](https://github.com/Optiboot/optiboot/blob/master/optiboot/bootloaders/optiboot/optiboot.c) adds a bit of delay before running the actual program, which is against the purpose of the project.

**But** as it turns out, there is actually [a problem](https://www.google.com/search?q=linux+dtr+problem&oq=linux+dtr+problem) with how `DTR` is handled on Linux, or maybe the [`ch341`](https://github.com/torvalds/linux/blob/master/drivers/usb/serial/ch341.c) serial driver for the chip I'm using.

I appreciate the project as a whole, nonetheless! 👍
