### ISSUE TITLE
Stty parameters error

### ISSUE THREAD

**Issue by OxMarco** [lepiaf/serialport#4]
In the command _stty -F_ the "F" should be lowercase

**Comment by lepiaf** [comment]
Hi,

I've tested on Ubuntu 16.04.4 LTS and raspbian. It is `stty -F /dev/ttyACM0 ...`.

Could you provide which operating system has `stty` with `-f`?

Thank you

**Comment by OxMarco** [comment]
Mac OS X

**Comment by lepiaf** [comment]
This PR will fix it https://github.com/lepiaf/serialport/pull/8

**Comment by lepiaf** [comment]
It is merged and I've tag v1.0.6
