### ISSUE TITLE
Memory usage after execute

### ISSUE THREAD

**Issue by beyzad-asa** [lepiaf/serialport#9]
Hey hey.

Thanks for this useful source.

Just tried it and realised the memory usage of the app will go extremely high after 3-4 minutes.

Looked up the source and found the issue.

You are creating an array named $chars and storing recieved data in it.

The problem is, even when there are no data, the array is filling will NULL and it increases its size.

Just converted it to a regular string and the problem is solved ;-)

**Comment by DevinNorgarb** [comment]
Yes, I have exactly the same issue @beyzad-asa ; 

@lepiaf Should I create a pull request for this to be fixed?

Thanks for this useful library BTW.

**Comment by lepiaf** [comment]
Hello,

Thank you for opening an issue. I've integrated your suggestion.

I've made a PR and release a new version. https://github.com/lepiaf/serialport/pull/12
